### ISSUE TITLE
Error in Centos 7?

### ISSUE THREAD

**Issue by prasanna224** [gregversteeg/bio_corex#13]
While running a randomly sampled file with around 40k rows where a few lines are given below in Centos 7 machine with the command below:

`python3 vis_corex.py /home/usr1/dx_eighth.csv --delimiter="|" --layers=16,8,1 --dim_hidden=3 --missing=-1e6 -c -b -v -o dx_sub --ram=72 --cpu=36`

 I am getting the following output in the end:

`TC at layer 1 is: 0.070
TC at layer 2 is: 0.346
Groups in sorted_groups.txt
Pairwise plots among high TC variables in "relationships"
vis_corex.py:174: FutureWarning: arrays to stack must be passed as a "sequence" type such as list or tuple. Support for non-sequence iterables such as generators is deprecated as of NumPy 1.16 and will raise an error in the future.
  all_edges = np.hstack(map(np.ravel, weights))
weight threshold is 0.000000 for graph with max of 100.000000 edges 
non-isolated nodes,edges 65 99
Error: remove_overlap: Graphviz not built with triangulation library
Error: remove_overlap: Graphviz not built with triangulation library
non-isolated nodes,edges 65 64
Error: remove_overlap: Graphviz not built with triangulation library
Error: remove_overlap: Graphviz not built with triangulation library
`

Is this expected behavior as the pdf files generated inside graphs folder inside the output folder appear to be errorneous and unclean?

Sample file:

DX101|DX110|DX115|DX118|DX142|DX143|DX155|DX160|DX166|DX169|DX175|DX184|DX196|DX212|DX215|DX218|DX222|DX223|DX234|DX235|DX239|DX253|DX254|DX267|DX271|DX275|DX277|DX278|DX279|DX295|DX298|DX310|DX315|DX332|DX335|DX342|DX343|DX344|DX356|DX385|DX386|DX399|DX404
8|0|1|6|0|0|0|0|0|0|0|0|5|0|3|0|0|6|0|453|0|0|0|2|0|0|6|0|0|0|9|4|6|0|0|1|1|0|9|0|0|41|81
0|4|0|0|0|4|1|0|53|0|0|2|0|0|1|0|0|0|0|0|0|4|0|0|0|0|3|0|0|0|0|0|11|0|4|0|0|0|0|0|7|0|0
0|0|0|0|0|0|0|0|0|0|1|0|0|0|0|0|0|0|0|0|0|1|0|0|0|0|0|0|0|0|0|0|0|0|0|0|0|0|0|0|0|0|0
0|0|0|0|1|0|0|0|0|0|0|0|0|0|9|0|0|3|0|0|0|0|0|0|0|0|0|2|0|0|2|0|25|0|0|0|0|0|0|0|2|0|0
.........
......

**Comment by gregversteeg** [comment]
vis_corex outputs a .dot file which is a network format for graphviz. Then it calls graphviz to compile a PDF image from the .dot file. Unfortunately, getting graphviz installed correctly is difficult, with platform specific issues. Please look at the new "troubleshooting graphviz" section of the readme to see if those steps help. You can try to manually run the graphviz compiling utility using statements like the one listed in the readme "sfdp tree.dot -Tpdf -Earrowhead=none -Nfontsize=12  -GK=2 -Gmaxiter=1000 -Goverlap=False -Gpack=True -Gpackmode=clust -Gsep=0.02 -Gratio=0.7 -Gsplines=True -o nice.pdf"

**Comment by prasanna224** [comment]
Thanks for your quick response. I have tried almost all possibilities but a nice output without error seems most elusive for CentOS 7.
