### ISSUE TITLE
Model serialization problem: AttributeError: 'Corex' object has no attribute 'pool'

### ISSUE THREAD

**Issue by cbpaw** [gregversteeg/bio_corex#23]
I am trying to use the model created with corex. However when loading the serialized object using pickle, I get the following error message when I am trying to use the transform method.

`AttributeError: 'Corex' object has no attribute 'pool'`

Could you help me using this model? I get great results using it in experiments!

**Comment by gregversteeg** [comment]
Hi, yes I remember having some issue with this too. 
I think is to set the class variable "pool" to None. Like this I think: 

corex_object = pickle.load(open(filename, 'rb'))
corex_object.pool = None


It has to do with the option for multi-threading that comes from this import:
from multiprocessing.dummy import Pool

But it's only useful for training, for transforming new data you don't usually need multiple CPUs.

**Comment by cbpaw** [comment]
Hi greg, 

This fixed the issue in my code! Thanks alot!
