### ISSUE TITLE
Could not convert string to float

### ISSUE THREAD

**Issue by HHalva** [gregversteeg/bio_corex#28]
Line 204 in` viz_corex.py` has:
`float(nx.__version__)`

This does not work since the version is '2.6.3' and hence can not convert to float as it's not a digit.

**Comment by HHalva** [comment]
For now, I changed the line to` float(nx.__version__.split('.')[0]) < 2`  to get it to work

**Comment by gregversteeg** [comment]
Thanks for catching this, that is a perfect fix. I updated the main repository.
